### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by wenxuan-xia** [lightxu/haowu#1]
你确定这不是好污吗

**Comment by lightxu** [comment]
shit...你不要想歪...

**Comment by wenxuan-xia** [comment]
LOL..

**Comment by lightxu** [comment]
欢迎贡献haowu...要给你加contributor吗

**Comment by wenxuan-xia** [comment]
what are you going to do?

**Comment by lightxu** [comment]
Basically this is just a collection of extremely useful tools I found during my development, or some interesting things to try. So each category will be a md file, and inside that is just a list of tool names, links and comments. As you can see in code_javascript.md ("code_" is used as a prefix to organize topics.)

**Comment by wenxuan-xia** [comment]
OK.. it's interesting. If I find anything interesting to contribute, I will start a pull-request.

**Comment by lightxu** [comment]
That works. :smile:
